slack:
  api:
    token: "${SLACK_AUTH_TOKEN:test-api-token}"
  url:
    open_im: "https://slack.com/api/im.open"
    user_info_by_email: "https://slack.com/api/users.lookupByEmail"
    post_message: "https://slack.com/api/chat.postMessage"
  callback_token: "${SLACK_CALLBACK_TOKEN:test-callback-token}"

google_sheets:
  url: "${GOOGLE_SHEETS_URL:}"
  token: "${GOOGLE_AUTH_TOKEN:test-sheets-token}"

spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"